### ISSUE TITLE
help docs not being generated

### ISSUE THREAD

**Issue by phaedrix** [spf13/PIV#2]
:helptags creates a tag file that only contains this:  
  /       apache-request-headers.txt      /_\/_  
NOT     strtr.txt       /_NOT_  
estimated       ifx-getsqlca.txt        /_estimated_  

PIV's are the only help files that have any issues.

**Comment by spf13** [comment]
I can confirm this. I'm working on the solution.

**Comment by spf13** [comment]
I've fixed this issue and updated the docs to the most recent from php.net
