### ISSUE TITLE
g:DisableAutoPHPFolding not working

### ISSUE THREAD

**Issue by renanivo** [spf13/PIV#20]
When I put `let g:DisableAutoPHPFolding = 1` in my .vimrc, it works for the first PHP file I open, but it is ignored in the next attempts.

I tested it in other computers with the same result.

I'm using MacVim version 7.3

**Comment by hackdon** [comment]
edit PIV/ftplugin/php.vim on line 41

let php_folding = 0

**Comment by adolfoabegg** [comment]
Thank you @dongxiong that solved the folding problem.
The weird thing is that having this line in .vimrc

``` vim
let g:DisableAutoPHPFolding = 1 
```

used to work

**Comment by abimaelmartell** [comment]
im having this same problem, do i have to edit the PIV/ftplugin/php.vim? 
I added this as a submodule to my dotfiles, and i dont think is a good idea edit the file :worried:

**Comment by kchr** [comment]
I have the same question. How do we use local (own) settings for php.vim without modifying the plugin code?

**Comment by bpearson** [comment]
to use local settings, PIV/ftplugin/php.vim should read:

if (!exists('php_folding'))
  let php_folding = 1
endif
