### ISSUE TITLE
Not an editor command: ^IEnableFastPHPFolds (vim 7.4)

### ISSUE THREAD

**Issue by ajpaulson** [spf13/PIV#26]
On opening any php file I receive the error:

```
Not an editor command: ^IEnableFastPHPFolds
```

Even if I disable the extra fold support.

**Comment by jojojames** [comment]
+1, happening with me too.

Using it as part of vim-polyglot though.

**Comment by ajpaulson** [comment]
@jojojames Actually I'm using through vim-polyglot - I'll check to see if this happens when using the plugin directly.
