### ISSUE TITLE
Syntax clearing issue

### ISSUE THREAD

**Issue by has2k1** [spf13/PIV#3]
Opening the first php file leads to a clear out of almost all the extra syntax settings set by other plugins. e.g. minibufexp, nerdtree(if `NERDTreeQuitOnOpen` is not set), easymotion, ...

Some of those plugins reload their syntax whenever their visibility is toggled on, others don't which handicaps the whole session as far as the later plugins are concerned.

This is the case because `syntax on` clears the syntax then loads only the buffer's filetype syntax file. Hence all other non filetype buffer windows lose their syntax.
Solution: Check if syntax is enabled before enabling it at [ftplugin/php.vim line 75](https://github.com/spf13/PIV/blob/master/ftplugin/php.vim#L75)

``` vim
if !exists("g:syntax_on") | syntax on | endif
```

The same issue is present when vimrc is resourced because of [.vimrc line 40](https://github.com/spf13/spf13-vim/blob/master/.vimrc#L40).

**Comment by spf13** [comment]
Thanks. Would you like to submit a pull request with this fix?

**Comment by has2k1** [comment]
Submitted one.

Plus, I found the php syntax file to be a regression from the system default save the php 5.3 ability. So many keyword groups are mixed which misleads the colorscheme.

I played about with it.  Check out my current [diff](https://github.com/has2k1/PIV/commit/69545c88998dfccedb09456e717558b258e10a82#diff-2).
