### ISSUE TITLE
E154: Duplicate tag "maxdb::store_result" in file .../PIV/doc//maxdb-store-result.txt

### ISSUE THREAD

**Issue by tachuris** [spf13/PIV#5]
This error is raised by pathogen#helptags.

The problem is maxdb-**stmt**-store-result.txt already defines tag maxdb::store_result (which probably should be maxdb_stmt_store_result)

**Comment by alemorozov** [comment]
Caught this error too. Seems there is a mistype
here http://php.net/manual/en/function.maxdb-stmt-store-result.php
or here http://www.php.net/manual/en/function.maxdb-store-result.php

**Comment by tachuris** [comment]
Reported the documentation problem: https://bugs.php.net/bug.php?id=61167
