### ISSUE TITLE
Malformed link in "Better Fold Support" section in README.md

### ISSUE THREAD

**Issue by hglattergotz** [spf13/PIV#7]
The link to http://www.vim.org/scripts/script.php?script_id=1623 includes a "]" and leads to an error on the target site vim.org

**Comment by spf13** [comment]
can you fork and issue a pull request with the fix?

**Comment by abackstrom** [comment]
This was resolved by #8

**Comment by ghost** [comment]
@hglattergotz : seems fixed now, can you close it?
